- name: Install Vagrant and Python3.5 from SCL
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - rh-python35
    - sclo-vagrant1

- name: Check Vagrant
  shell: '{{ vagrant_scl_exec }} vagrant --version'
  become: true

- name: Install Packages
  yum:
    name: '{{ item }}'
    state: present
  become: true
  with_items:
    - libvirt
    - libvirt-devel
    - kvm
    - seabios
    - git
    - gcc
    - libffi-devel
    - openssl-devel
    - patch
    - libguestfs-tools-c
    - nmap

- name: Run VMs under root
  lineinfile:
    dest: /etc/libvirt/qemu.conf
    line: 'user = "root"'

- name: Enable libvirtd service
  service:
    name: libvirtd
    state: started
    enabled: yes

- name: Install Pipsi into the Python 3 SCL
  shell: '{{ python3_scl_exec }} pip3.5 install pipsi'
  become: true

- name: Install Python-level test dependencies
  shell: '{{ python3_scl_exec }} pip3.5 install -r integration-tests/requirements.txt'
  args:
    chdir: /root/payload
  become: true
