# file: roles/init/tasks/main.yml
---

- name: Set up firewall
  shell: systemctl enable firewalld

- name: Start the firewall
  shell: systemctl start firewalld

- name: Update Yum
  yum: name=* state=latest

- name: Install nano, git, etc
  yum: pkg={{ item }} state=installed
  with_items:
     - git
     - nano
     - curl
     - gcc
     - kernel-devel
     - wget
     - vim
     - man
     - unzip

- name: Install SELinux bindings for Ansible
  yum: pkg=libselinux-python state=installed

- name: Add current user's default RSA SSH key
  authorized_key:
    user: vagrant
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
