# file: roles/mysql/tasks/install.yml

- name: MySql packages are installed
  yum: pkg={{ item }}
  with_items:
    - mysql-server
    - mysql
    - MySQL-python

- name: Start the MySQL service
  service: name=mysqld state=started enabled=true
