---

# Create a `ci` account with the following properties
# - vagrant and libvirt group membership
# - known ssh key in authorized_keys
#
# Also configure the `root` user to have a well known authorized_keys key

- name: Create `le-app-ci` account
  user:
    name: le-app-ci
    groups: vagrant,libvirt
    comment: "Le-App CI Account"
  become: true

- name: Ensure passwordless sudo for the `le-app-ci` user
  shell: 'echo "le-app-ci       ALL = (ALL) NOPASSWD: ALL" >> /etc/sudoers.d/le-app-ci'
  become: true

- name: Ensure proper chmod on /etc/sudoers*
  file:
    state: file
    path: /etc/sudoers.d/{{ item }}
    mode: 0440
  with_items:
    - 'vagrant'
    - 'le-app-ci'
  become: true

- name: Ensure `sudo` configuration is alright
  shell: visudo -c
  become: true

- name: Set SSH access for CI Account
  authorized_key:
    user: le-app-ci
    state: present
    key: "{{ lookup('file', lookup('env','LE_APP_SECRETS_DIR') + 'ssh/ci/id_rsa.pub') }}"
  become: true

- name: Set SSH access for root Account
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', lookup('env','LE_APP_SECRETS_DIR') + 'ssh/root/id_rsa.pub') }}"
  become: true
