- name: Update Yum
  yum:
    name: '*'
    state: latest

- name: Install nano, git, etc
  yum:
    name: '{{ item }}'
    state: installed
  with_items:
     - git
     - nano
     - curl
     - gcc
     - kernel-devel
     - wget
     - vim
     - man
     - unzip

- name: Install SELinux bindings for Ansible
  yum:
    name: libselinux-python
    state: installed

- name: Add the predefined SSH key
  authorized_key:
    user: '{{ item }}'
    state: present
    key: "{{ lookup('file', '{{ key_path }}') }}"
  with_items:
    - vagrant
    - root
