- hosts: all
  roles:
    - role: init
      key_path: ../../../integration-tests/config/leappto_testing_key.pub
    - httpd
    - role: scl
    - { role: mysql,  package_name: "mysql55", service_name: "mysql55-mysqld"}
    - role: php
      repo_version: 6
    - phpmyadmin
