# file: ansible/roles/vagrant/install.yml
---

# For some reason this task gets always skipped :/
#- name: "Install Vagrant from SCL"
#  include_role:
#    name: smbambling.scl
#    tasks_from: packages
#  vars:
#    scl_packages:
#      - {name: 'sclo-vagrant1'}

- name: Install Vagrant & Python3.5 from SCL
  shell: 'yum install -y centos-release-scl 
       && yum-config-manager -y --add-repo=http://mirror.centos.org/centos-7/7/sclo/x86_64/sclo/ 
       && yum install -y sclo-vagrant1 rh-python35 
       && echo "source /opt/rh/rh-python35/enable" | tee -a /root/.bashrc
       && echo "source /opt/rh/sclo-vagrant1/enable" | tee -a /root/.bashrc
       && echo "export PATH=\$PATH:/root/.local/bin/" >> /root/.bashrc'
  become: true

- name: Install EPEL
  yum: pkg=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present
  become: true

- name: Install Packages
  yum: pkg={{ item }} state=present
  become: true
  with_items:
    - libvirt
    - ansible
    - git
    - gcc
    - libffi-devel
    - openssl-devel

- name: Install Behave and Pipsi
  pip:
    executable: pip3.5
    name: 
     - behave
     - pipsi
  become: true
  become_flags: -i

- name: Install Pew
  shell: pipsi install pew
  become: true
  become_flags: -i

- name: Install Pipenv
  shell: pipsi install pipenv
  become: true
  become_flags: -i

# TODO: Find a better place for this one
- name: Chek Vagrant
  shell: vagrant --version
  become: true
  become_flags: -i

- name: Checkout `le-app-to` code
  git:
    repo: 'https://github.com/leapp-to/prototype/'
    dest: /srv/le-app
  become: true

- name: Prepare `pipenv`
  shell: pipenv --three && pipenv install --ignore-hashes
  args:
    chdir: /srv/le-app
  become: true
  become_flags: -i
